
import __ASTRO_IMAGE_IMPORT_1mPKqS from "./orgcon19-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2019-10%2Forgcon%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2fMogj from "./heading.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2020-01%2Fbackstopjs-tutorial%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZpgAR8 from "./youfirst-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2020-01%2Fyou-first-review%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1uxyxl from "./intro-to-rust-codebar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-04%2Fintro-to-rust-talk%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ztG0j from "./banner-study-group.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2021-05%2Fstudy-group%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z25kKYM from "./macros-thursdays-matter.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-05%2Fmacros-what-why-how%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z21iUvn from "./logo_header.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-02%2Frust-nation%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1R4dPc from "./chatgpt-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-12%2Fchatgpt%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z2hsiQF from "./code-retreat-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-12%2Fcode-retreat%2Findex.md";
import __ASTRO_IMAGE_IMPORT_13BY2v from "./screenkata_header.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-05%2Frust-screenkatas%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1utUkJ from "./intro_to_tdd_header.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-06%2Fintro-to-tdd%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1Pse4o from "./angular-migration-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-06%2Fangular-migration%2Findex.md";
import __ASTRO_IMAGE_IMPORT_1lPyiJ from "./devox_24_talk_banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2024-05%2Fdevoxx-uk-24%2Findex.md";
import __ASTRO_IMAGE_IMPORT_oc0Jt from "./mechanical-turk.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2024-02%2Fllms-overpromised%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z10kG2s from "./sock-puppet.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-04%2Fclaude-code%2Findex.md";
import __ASTRO_IMAGE_IMPORT_Z1NlgKn from "./dotfiles-output.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-04%2Fdotfiles%2Findex.md";
import __ASTRO_IMAGE_IMPORT_ZqvB0y from "./painted_shed.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-04%2Fdotfiles%2Findex.md";
export default new Map([["./orgcon19-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2019-10%2Forgcon%2Findex.md", __ASTRO_IMAGE_IMPORT_1mPKqS], ["./heading.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2020-01%2Fbackstopjs-tutorial%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2fMogj], ["./youfirst-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2020-01%2Fyou-first-review%2Findex.md", __ASTRO_IMAGE_IMPORT_ZpgAR8], ["./intro-to-rust-codebar.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-04%2Fintro-to-rust-talk%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1uxyxl], ["./banner-study-group.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2021-05%2Fstudy-group%2Findex.md", __ASTRO_IMAGE_IMPORT_ztG0j], ["./macros-thursdays-matter.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-05%2Fmacros-what-why-how%2Findex.md", __ASTRO_IMAGE_IMPORT_Z25kKYM], ["./logo_header.jpeg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-02%2Frust-nation%2Findex.md", __ASTRO_IMAGE_IMPORT_Z21iUvn], ["./chatgpt-banner.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-12%2Fchatgpt%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1R4dPc], ["./code-retreat-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2022-12%2Fcode-retreat%2Findex.md", __ASTRO_IMAGE_IMPORT_Z2hsiQF], ["./screenkata_header.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-05%2Frust-screenkatas%2Findex.md", __ASTRO_IMAGE_IMPORT_13BY2v], ["./intro_to_tdd_header.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-06%2Fintro-to-tdd%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1utUkJ], ["./angular-migration-banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2023-06%2Fangular-migration%2Findex.md", __ASTRO_IMAGE_IMPORT_1Pse4o], ["./devox_24_talk_banner.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2024-05%2Fdevoxx-uk-24%2Findex.md", __ASTRO_IMAGE_IMPORT_1lPyiJ], ["./mechanical-turk.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2024-02%2Fllms-overpromised%2Findex.md", __ASTRO_IMAGE_IMPORT_oc0Jt], ["./sock-puppet.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-04%2Fclaude-code%2Findex.md", __ASTRO_IMAGE_IMPORT_Z10kG2s], ["./dotfiles-output.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-04%2Fdotfiles%2Findex.md", __ASTRO_IMAGE_IMPORT_Z1NlgKn], ["./painted_shed.jpg?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2F2026-04%2Fdotfiles%2Findex.md", __ASTRO_IMAGE_IMPORT_ZqvB0y]]);
		