version: '3'
services:
  website:
    image: httpd:2.4
    ports:
      - "8000:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs/

  visual-regression-tests:
    build: ./tests/visual
    volumes:
      - ./tests/visual:/src
    links: 
      - website
