import { visit } from 'unist-util-visit';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load placeholders manifest (generated by copy-figure-images integration)
let placeholders = {};
try {
  const manifestPath = path.join(__dirname, 'figure-placeholders.json');
  placeholders = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
} catch {
  // No manifest yet — first build
}

/**
 * Rehype plugin that transforms custom <figure> elements in markdown.
 * Includes blur-up placeholders from the generated manifest.
 */
export default function rehypeFigure() {
  return (tree, file) => {
    const filePath = file.history?.[0] || '';
    const match = filePath.match(/content\/blog\/(.+?)\/index\.md$/);
    const postSlug = match ? match[1] : '';

    visit(tree, 'element', (node, index, parent) => {
      if (node.tagName !== 'figure') return;
      if (!node.properties?.src) return;

      const src = node.properties.src;
      const alt = node.properties.alt || '';
      const width = node.properties.width || '100%';

      const imagePath = `/_figure-images/${postSlug}/${src}`;
      const placeholder = placeholders[imagePath] || '';

      // Wrapper div with blur-up placeholder as background
      const placeholderStyle = placeholder
        ? `background-image: url(${placeholder}); background-size: cover; background-position: center;`
        : '';

      const imgNode = {
        type: 'element',
        tagName: 'img',
        properties: {
          src: imagePath,
          alt: alt,
          style: 'width: 100%',
          loading: 'lazy',
          class: 'figure-img',
        },
        children: [],
      };

      const linkNode = {
        type: 'element',
        tagName: 'a',
        properties: {
          href: imagePath,
          target: '_blank',
          rel: 'noreferrer',
        },
        children: [imgNode],
      };

      const imgWrapper = {
        type: 'element',
        tagName: 'div',
        properties: {
          class: 'img-placeholder',
          style: placeholderStyle,
        },
        children: [linkNode],
      };

      const figureChildren = [imgWrapper];

      if (node.children && node.children.length > 0) {
        figureChildren.push({
          type: 'element',
          tagName: 'figcaption',
          properties: {},
          children: node.children,
        });
      }

      const newFigure = {
        type: 'element',
        tagName: 'figure',
        properties: {},
        children: figureChildren,
      };

      const wrapper = {
        type: 'element',
        tagName: 'div',
        properties: {
          id: 'content-figure',
          style: `width: ${width}; margin: 0 auto`,
        },
        children: [newFigure],
      };

      parent.children[index] = wrapper;
    });
  };
}
