name: Run tests
on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install build-essential

      - name: Install more build dependencies
        run: sudo apt-get install make gcc*

      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Node Dependencies
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: install

      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: test

      - name: Build Site
        uses: borales/actions-yarn@v2.1.0
        with:
          cmd: build

      - name: Run Visual Regression Tests
        run: ./scripts/run-visual-regression-tests.sh

      - name: Package Visual Regression Tests Report
        if: failure()
        run: tar -zcvf tests/visual/report.tar.gz tests/visual/backstop_data

      - name: Archive Visual Regression Tests Report
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: visual-regression-tests-report.tar.gz
          path: tests/visual/report.tar.gz
