name: Run tests
on: [push]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Run Unit Tests
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test

      - name: Build Site
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Run Visual Regression Tests
        run: ./scripts/run-visual-regression-tests.sh
