name: Run tests
on: [push]

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Install Project Dependencies
        run: yarn install

      - name: Run Unit Tests
        run: yarn test

      - name: Build Site
        run: yarn build

      - name: Run Visual Regression Tests
        run: ./scripts/run-visual-regression-tests.sh
        if: ${{ false }}

      - name: Package Visual Regression Tests Report
        if: failure()
        run: tar -zcvf tests/visual/report.tar.gz tests/visual/backstop_data

      - name: Archive Visual Regression Tests Report
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: visual-regression-tests-report.tar.gz
          path: tests/visual/report.tar.gz
